### ISSUE TITLE
Dataset download URL broken

### ISSUE THREAD

**Issue by zarifikram** [ALRhub/MTS3#1]
None of the download URLs work. Any solution to this?

**Comment by vaisakh-shaj** [comment]
Hello sorry for the delay in responding... I will be updating the broken URL by the end of the week... Thank you for letting me know.

**Comment by vaisakh-shaj** [comment]
New googledrive URL for the datasets can be found in [here ](https://github.com/ALRhub/MTS3/blob/master/dataFolder/mts3_datasets_processed/readme.md ). It should automatically be downloaded using gdown when you run the script. Let me know if you have any further issues.
